---
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:react/jsx-runtime
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: './tsconfig.json'
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
settings:
  import/resolver:
    typescript:
      project: './tsconfig.json'
  react:
    version: detect
rules:
  arrow-body-style:
    - error
    - as-needed
  '@typescript-eslint/explicit-function-return-type': warn
  '@typescript-eslint/triple-slash-reference': warn
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-non-null-assertion': warn
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
  react/button-has-type: error
  react/no-array-index-key: warn
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: warn
  prettier/prettier:
    - error
    - jsxSingleQuote: true
      singleQuote: true
      semi: false
      tabWidth: 2
      trailingComma: all
      bracketSameLine: false
      useTabs: true
      arrowParens: always
      endOfLine: auto
